# Algebra lineal con numpy
Raul Marusca raulrm@gmail.com

github: https://github.com/raulrm/algebra_numpy

LinkedIn: https://www.linkedin.com/in/raul-marusca

## Contenido
1. Notación y contenidos básicos  
    1. Notación básica
    2. Contenidos básico
    3. Escalares
    4. Vectores
    5. Matrices
  
2. Multiplicación de Matrices
    1. Producto entre vectores
    2. Producto entre vector y matriz
    3. Producto entre matrices
  
3. Operaciones  
    1. La matriz identidad y la matriz diagonal
    2. Transposición
    3. Matrices simétricas
    4. Traza
    5. Norma
    6. Independencia lineal y Rango
    7. Inversa de una matriz 
    8. Matrices ortogonales 
    9. El determinante
    10. Formas cuadráticas 
    11. Matrices semi-definidas positivas
    12. AutoValores y AutoVectores
    13. AutoValores y AutoVectores de matrices simétricas  
4. Calculo matricial
    1. Gradiente
    2. Hessiano
    3. Gradiente y Hesiano de formas cuadráticas y lineales
    4. Mínimos cuadrados
    5. Gradiente y Determinante
    6. AutoValores como optimizadores

In [1]:
import numpy as np

## Notación y contenidos básicos


### Notacion Basica

### Escalares
En algebra, los escalares son los números con los que trabajamos en el dia a dia.  
Son representados por un numero simple y usando letras minúsculas.  
Ejemplos de escalares son:
- $x \in \mathbb{R}$ - Numero real
- $z \in \mathbb{Z}$ - Numero entero
- $y \in \{0,1,...C\}$ - Conjunto finito
- $u \in [0,1]$ - Conjunto cerrado

En código los podemos ver como:

In [2]:
x = 1.2345
print(x)
z = int(4)
print(z)


1.2345
4


Numpy no tiene una forma directa de definir Conjuntos. Para solucionar eso debemos emplear código que compruebe los valores limites de cada variable.  

#### Suma escalares
Es la suma comun 
$$a+b = c$$
Tembien definiendo el *negativo* podemos definir la resta
$$a + (-b) = c$$
$$a-b = c$$

In [3]:
# En python (funciona con enteros y de coma flotante)
# Tambien con complejos pero no veremos ese type
a = 4
b = 2
c = a + b
print(c) 

c = a - b
print(c) 

6
2


#### Multiplicacion de escalares
La multiplicación, explicada de forma sencilla, consiste en que cuando multiplicamos, por ejemplo, 6×2, estaríamos realizando la siguiente operación 6+6. En otro caso, si multiplicásemos 5×7, estaríamos sumando 5+5+5+5+5+5+5 (sumado 7 veces el numero 5)  
Un caso especial es cuando el o los escalares que estamos multiplicando no son numeros enteros. Que tiene varias formas de resolverse.  
Se nomina como:  
$$a \cdot b= c$$
Veamos como se multiplican dos o mas escalares en python 

In [4]:
# Definamos los escalares
a = 4
b = 2
# Y la operacion
c = a*b
print(c)

8


### Vectores
Usualmente consideramos a los vectores como vectores **columna**. Se muestran como letras en minuscula y ocasionalmente con letras en negrita.  
La dimension se describe con las letras $d$, $D$, $n$ o $p$ Nosotros usaremos $n$  
Cada uno de los elementos que componen el vector se determinan por un subindice $x_i$  
Un vector de componentes real se denota como:  
$$\textbf{x} \in \mathbb{R}^n$$
En su forma columna
$$\textbf{x} = \begin{bmatrix} x_{1}\\x_{2}\\x_{3}\\\vdots\\x_{d}\end{bmatrix}$$
o en su forma traspuesta  
$$x = ( x_{1},x_{2},x_{3},\dots,x_{d} )^T$$  

En *Python* los vectores se pueden definir con listas o conjuntos, pero estas estructuras de datos nativas no tienen todos los metodos matematicos necesarios para operar algebraicamente. Y seria necesario desarrollar mucho codigo para ello.   
Por suerte ese codigo ya esta escrito y optimizado en algunas librerias adicionales, nosotros vamos a usar la libreria *numpy* y alli los vectores se definen con el metodo **.array()**  
Veamos como:

In [5]:
# Primero creamos una lista con loscomponentes del vector 
# (o la puede generar nuestro programma)
valores_x = [8.9, 2.5, 23.4,17.7, 11, 4, 13]
# Luego iniciamos el array
x = np.array(valores_x)
print(x)

[ 8.9  2.5 23.4 17.7 11.   4.  13. ]


In [6]:
# Tambien podemos crearlo directamente
x = np.array([8.9, 2.5, 23.4,17.7, 11, 4, 13])
print(x)

[ 8.9  2.5 23.4 17.7 11.   4.  13. ]


Podemos ver como *numpy* detecta que el tipo mas conveniente para todos los elementos del array es *float*  
Esto se puede cambiar definiendo el *tipo*  con el que se va a guardar cada elemento.  
Recordemos que las listas en Python pueden tener elementos de cualquier tipo (o sea son **heterogeneas**), en los arrays numpy siempre son del mismo tipo. 
Definimos el tipo a utilizar usando el parametro *dtype=*

In [7]:
# creamos un array de elementos enteros
x = np.array([8, 2, 23,17, 11, 4, 13], dtype=np.int64)
print(x)

[ 8  2 23 17 11  4 13]


np.int64 es un numero entero con signo de 64 bits. Hay muchos otros y siempre debemos usar el correcto para la aplicacion que estamos creando.  
Para ver cuales tipos estan disponibles podemos hacer:  

In [8]:
# listar todos los tipos numericos que soporta numpy
np.sctypes

{'int': [numpy.int8, numpy.int16, numpy.int32, numpy.int64],
 'uint': [numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64],
 'float': [numpy.float16, numpy.float32, numpy.float64, numpy.float128],
 'complex': [numpy.complex64, numpy.complex128, numpy.complex256],
 'others': [bool, object, bytes, str, numpy.void]}

numpy ademas tiene otras formas para crear arrays con funciones que lo crean vacios o con algun valor predefinido.  
Veamos cuales son:  
1. Arange() arange(comienzo, fin, paso, dtype) Nunca incluye el valor *fin* en el array

In [9]:
# Arrays con un rango de valores
array_arange = np.arange(10)
print(array_arange)

[0 1 2 3 4 5 6 7 8 9]


Extendemos un poco mas el ejemplo generando un array de numeros impares

In [10]:
# Arrays con un rango de valores con primer valor, valor final y paso
# aprovechamos para definir un tipo de datos
array_arange = np.arange(1, 10, 2, dtype=np.int8)
print(array_arange)

[1 3 5 7 9]


2. Linspace() linspace(comienzo, fin, cantidad, dtype) Siempre incluye *comienzo* y *fin* en el array

In [11]:
# genera cantidad de valores entre dos limites
array_linspace = np.linspace(1., 10., 5)
print(array_linspace)

[ 1.    3.25  5.5   7.75 10.  ]


Ahora que ya sabemos como crear array de 1 dimension (o $\mathbb{R}^n$) vamos a ver como podemos realizar algunas operaciones matematicas con ellos

#### Suma de escalar y vector
En algebra comun definimos a la suma de un escalar con un vector como:  
Sea *a* un escalar y $x=(x_1, x_2,...x_n)^T$ un vector de dimension *n* la suma $y=a+x$ es igual a:  

$$\textbf{y} = a +  \begin{bmatrix} x_{1}\\x_{2}\\x_{3}\\\vdots\\x_{n}\end{bmatrix}= \begin{bmatrix} a +x_{1}\\a+x_{2}\\a+x_{3}\\\vdots\\a+x_{n}\end{bmatrix}$$   
O sea que $y$ es tambien un vector de dimension $n$  
Notemos tambien que la suma es **conmutativa** es decir, que $a+x=x+a$  

Hagamos un ejemplo numerico:  
Sea $a=5$ y $x=(4, 3, -5)^T$
$$\textbf{y} = 5 +  \begin{bmatrix} 4\\3\\-5\end{bmatrix}= \begin{bmatrix} 5 +4\\5+3\\5+(-5)\end{bmatrix}= \begin{bmatrix} 9\\8\\0\end{bmatrix}$$ 
Veamos como es esto en python  

In [12]:
# Primero el escalar
a = 5
# Ahora el array
x = np.array([4, 3, -5], dtype=np.int64)
# Hacemos la cuenta
y = a + x
print(y)

[9 8 0]


#### Suma de Vectores
Definimos a la suma de vectores como: 
Sea $x=(x_1, x_2,...x_n)^T$ un vector de dimension *n* y sea $y=(y_1, y_2,...y_n)^T$ **tambien** un vector de dimension **n** (notese que esto es importante, ambos deben ser de la misma dimension) decimos entonces que $w=x+y$ es tambien un vector de dimension *n* cuyos elementos son:  

$$\textbf{w} = x+ y =\begin{bmatrix} x_{1}\\x_{2}\\x_{3}\\\vdots\\x_{n}\end{bmatrix} + \begin{bmatrix} y_{1}\\y_{2}\\y_{3}\\\vdots\\y_{n}\end{bmatrix}= \begin{bmatrix} x_{1} + y_1\\x_{2} + y_2\\x_{3}+y_3\\\vdots\\x_{n}+y_n\end{bmatrix}$$  
Podemos apreciar tambien que la suma de vectores es conmutativa, es decir: $x+y=y+x$  

Vayamos a un ejemplo con valores  
Sea $x=(6, 3, 5, 4)^T$ y $y=(2, -1, 4, 8)^T$

$$\textbf{w} = x+ y =\begin{bmatrix} 6\\3\\5\\4\end{bmatrix} + \begin{bmatrix} 2\\-1\\4\\8\end{bmatrix}= \begin{bmatrix} 6 + 2\\3+(-1)\\5+4\\4+8\end{bmatrix}= \begin{bmatrix} 8\\2\\9\\12\end{bmatrix}$$  

En codigo:

In [13]:
# Hacemos x
x = np.array([6, 3, 5, 4], dtype=np.int64)
# Hacemos y
y = np.array([2, -1, 4, 8], dtype=np.int64)
# realizamos la suma de vectores
w = x +y 
print(w)

[ 8  2  9 12]


#### Multiplicacion de escalar y vector
En algebra comun definimos a la multiplicacion de un escalar con un vector como:  
Sea *a* un escalar y $x=(x_1, x_2,...x_n)^T$ un vector de dimension *n* el producto $y=a\,x$ es igual a:  

$$\textbf{y} = a\,\begin{bmatrix} x_{1}\\x_{2}\\x_{3}\\\vdots\\x_{n}\end{bmatrix}= \begin{bmatrix} a\,x_{1}\\a\,x_{2}\\a\,x_{3}\\\vdots\\a\,x_{n}\end{bmatrix}$$   
O sea que $y$ es tambien un vector de dimension $n$  
Notemos tambien que el producto es **conmutativo** es decir, que $a\,x=x\,a$  

Hagamos un ejemplo numerico:  
Sea $a=5$ y $x=(4, 3, -5)^T$
$$\textbf{y} = 5\,\begin{bmatrix} 4\\3\\-5\end{bmatrix}= \begin{bmatrix} 5\;4\\5\;3\\5\,(-5)\end{bmatrix}= \begin{bmatrix} 20\\15\\-25\end{bmatrix}$$ 
Veamos como es esto en python 

In [14]:
# Hacemos el escalar
a = 5
# Hacemos x
x = np.array([4, 3, -5], dtype=np.int64)
# realizamos la suma de vectores
y = a*x 
print(y)

[ 20  15 -25]


#### Multiplicacion de Vectores
Ok, aqui ya entramos en algunos problemas. Es que existen tres formas de hacer el producto entre vectores:
1. **Producto entre elementos** es cuando cada elemento de cada vector se multilica por el correspondiente del otro vector
2. **Producto Interno** es cuando multiplicamos dos vectores y nuestro resultado es un escalar.
3. **Producto Externo** es cuando multiplicamos dos vectores y nuestro resultado otro vector o matriz.  

Veamos como es eso  
##### <ins>Producto entre elementos</ins>
Se define al producto entre elementos de dos vectores $x=(x_1, x_2,...x_n)^T$ y $y=(y_1, y_2,...y_n)^T$ al vector $v$ que surge de realizar
$$v_i = x_1 * y_i$$  
  
$$v = x * y =\begin{bmatrix} x_{1}\\x_{2}\\x_{3}\\\vdots\\x_{n}\end{bmatrix} * \begin{bmatrix} y_{1}\\y_{2}\\y_{3}\\\vdots\\y_{n}\end{bmatrix}=\begin{bmatrix} x_{1} \; y_1\\x_{2}\;y_2\\x_{3}\;y_3\\ \vdots \\ x_{n}\;y_n \end{bmatrix}$$  
Podemos notar que este producto es **conmutativo** es decir $x * y=y * x$
En python se emplea el simbolo *
Notemos que ya usamos este metodo cuando multiplicamos un vector por un escalar. Lo que sucede es que cuando empleamos la muktiplicacion estandar y uno de los elementos a multiplicar es un vector, Python convierte al escalar en un vector del mismo largo que el otro. A este proceso (que tambien sucede en la suma de escalar y vector) se lo llama **broadcasting**

In [15]:
# Definimos x 
x = np.array([4, 3, -5], dtype =np.int64)
# definimos y 
y = np.array([2, -1, 4], dtype =np.int64)
# Ahora realizamos la operacion
v = x * y
print(v)

[  8  -3 -20]


##### <ins>Producto interno</ins>
Se define al producto interno entre dos vectores $x=(x_1, x_2,...x_n)^T$ y $y=(y_1, y_2,...y_n)^T$ al escalar $v$ que surge de realizar
$$v = \sum_{i=1}^n x_i\;y_i$$
O de otra forma
$$v = x \cdot y =\begin{bmatrix} x_{1}\\x_{2}\\x_{3}\\\vdots\\x_{n}\end{bmatrix} \cdot \begin{bmatrix} y_{1}\\y_{2}\\y_{3}\\\vdots\\y_{n}\end{bmatrix}= x_{1} \; y_1+x_{2}\;y_2+x_{3}\;y_3+ \cdots + x_{n}\;y_n$$  
Podemos notar que este producto es **conmutativo** es decir $x\cdot y=y\cdot x$  

Tambien tenemos una forma mas concisa para denotar al producto interno usando notacion matricial
$$v= x^Ty$$
$$v = x^Ty = [x_{1},x_{2},x_{3},\dots,x_{n}]\begin{bmatrix} y_{1}\\y_{2}\\y_{3}\\\vdots\\y_{n}\end{bmatrix}=\sum_{i=1}^n x_i\;y_i$$  
Se puede tambien expresar esta operacion como  
$$x^T y = y^T x$$


El producto interno tambien es conocido por *producto punto* 

Hagamos esa cuenta con valores  
Sea $x=(4, 3, -5)^T$ y $y=(2, -1, 4)^T$, entonces:  
$$v = x \cdot y =\begin{bmatrix} 4\\3\\-5\end{bmatrix} \cdot \begin{bmatrix} 2\\-1\\4\end{bmatrix}= 4 \cdot 2+3\cdot (-1)+(-5)\cdot 4 = 8-3-20 = -15$$  
En Python para realizar esta operacion se emplea el metodo *np.inner(array1, array2)* (tambien existe el alias *np.dot()*)

In [16]:
# Definimos x 
x = np.array([4, 3, -5], dtype =np.int64)
# definimos y 
y = np.array([2, -1, 4], dtype =np.int64)
# Ahora realizamos la operacion
v = np.inner(x, y)
print(v)

-15


np.inner() tambien admite la multiplicacion de escalares. De paso mostramos que *np.dot()* funciona igual

In [17]:
# Definimos los escalares
a, b = 4, 2
# Hacemos el producto inner
c = np.inner(a, b)
print(c)
# Hacemos el producto dot
c = np.dot(a, b)
print(c)

8
8


##### <ins>Producto externo</ins>
Se define al producto punto entre dos vectores $x=(x_1, x_2,...x_m)^T$ y $y=(y_1, y_2,...y_n)^T$ (*n* y *m* pueden tener valores distintos) a la matriz de dimensiones *m x n* que resulta de hacer  
$$xy^T = \begin{bmatrix} x_{1}\\x_{2}\\x_{3}\\\vdots\\x_{m}\end{bmatrix} [y_1, y_2, y_3, \dots, y_n ] = \begin{bmatrix} x_1 y_1& x_1 y_2& x_1 y_3 & \cdots & x_1 y_n \\ x_2 y_1& x_2 y_2& x_2 y_3 & \cdots & x_2 y_n \\ x_3 y_1& x_3 y_2& x_3 y_3 & \cdots & x_3 y_n \\ \vdots & \vdots & \vdots & \cdots & \vdots\\ x_m y_1& x_m y_2& x_m y_3 & \cdots & x_m y_n \end{bmatrix}$$
Notemos que el resultado es una matriz.  
  
En *numpy* se emplea el metodo *np.outer(array1, array2)*

In [18]:
# Definimos x 
x = np.array([4, 3, -5], dtype =np.int64)
# definimos y 
y = np.array([2, -1, 4], dtype =np.int64)
# Ahora realizamos la operacion
v = np.outer(x, y)
print(v)

[[  8  -4  16]
 [  6  -3  12]
 [-10   5 -20]]


##### <ins>Otras operaciones</ins>
Estamos dejando de lado otros *productos vectoriales* que estan incluidos en *numpy* Uno de los mas notorios es el **producto cruz** que nos permite encontrar el vector perpendicular a otros dos vectores (esto funciona en otras dimensiones tambien)  
En numpy usamos el metodo *np.cross(x,y) para calcularlo

### Matrices
Como ya hemos visto, las matrices son arreglos bidimensionales de numeros.  
Por lo general se las denomina con una letra en mayuscula  
Y se accede a sus elementos empleando dos indices (el vertical y el horizontal) $X_{ij}$ o $x_{ij}$  
Unos ejemplos son:
$$X \in \mathrm{R}^{m\times n}$$  
$$V = \begin{bmatrix} 8 & -4 & 16\\ 6& -3& 12\\-10& 5& -20\end{bmatrix}$$  

Las notaciones mas comunes son:
$$A = \begin{bmatrix} a_{1,1}&a_{1,2}&\cdots& a_{1,n}\\ a_{2,1}&x_{2,2}&\cdots& a_{2,n}\\ \vdots & \vdots & \cdots & \vdots  \\  a_{m,1}&a_{m,2}&\cdots& a_{m,n} \end{bmatrix}$$  
  
$$B = \sum_{i=1,j=1}^{m,n} b_{ij}$$
  
En *numpy* las matrices son un caso de array con 2 dimensiones  
Para crear una matriz con *numpy* disponemos de varias formas:  
. Concatenando arrays

In [19]:
# Definimos 4 arrays de 4 elementos
array1 = [0,1,2,3]
array2 = [4, 5, 6, 7]
array3 = [8, 9, 10, 11]
array4 = [12, 13, 14, 15]
# contruimos el array multidimensional con el metodo *.array()*
matriz1 = np.array([array1, array2, array3, array4])
# Mostramos como quedo
print(matriz1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


. Redimensionando un array existente con el metodo *.reshape()* 

In [20]:
# Creamos un array de una dimension con el metodo .arange()
array_1d = np.arange(16)
# Ahora modificamos sus dimensiones de 1x16 a 4x4
matriz1 = array_1d.reshape(4,4)
# Mostramos como quedo
print(matriz1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


. Creando matrices vacias o unitarias y multiplicando por un escalar  
Para ello usaremos los metodos *.zeros()* y *ones()* Ambos requieren que le pasemos las dimensiones en una tupla y que indiquemos de que tipo van  a ser sus elementos.

In [21]:
# Creamos una matriz de 3x3 con todos sus elementos en cero
matriz0 = np.zeros((3,3), dtype=int)
# Lo mostramos
print(matriz0)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [22]:
# Creamos una matriz de 3x3 con todos sue elementos en 1
matriz1 = np.ones((3,3), dtype=int)
# Lo mostramos
print(matriz1)


[[1 1 1]
 [1 1 1]
 [1 1 1]]


#### Transposicion 
La operacion mas basica que podemos realizar con una matriz es la de *trasponerla* Esto consiste en intercambiar filas por columnas.  
La operacion se denota con una letra T o t "elevando" a la matriz
$$A^T$$ 
Esto ya lo vimos en vectores cuando transponiamos un vector columna a un vector fila  
En matrices seria:  

$$ X = \begin{bmatrix} x_{1,1}&x_{1,2}&\cdots& x_{1,n}\\ x_{2,1}&x_{2,2}&\cdots& x_{2,n}\\ \vdots & \vdots & \cdots & \vdots  \\  x_{m,1}&x_{m,2}&\cdots& x_{m,n} \end{bmatrix} \qquad X^T = \begin{bmatrix} x_{1,1}&x_{2,1}&\cdots& x_{m,1}\\ x_{1,2}&x_{2,2}&\cdots& x_{m,2}\\ \vdots & \vdots & \cdots & \vdots  \\  x_{1,n}&x_{2,n}&\cdots& x_{m,n} \end{bmatrix}$$
  
Esta operacion en numpy se hace con el metodo .T de la matriz o vector

In [23]:
# Creamos una matriz cuadrada de 3x3
A = np.arange(9).reshape(3,3)
# La mostramos
print(A)
# Ahora la trasponemos
A = A.T
# Y la volvemos a mostrar traspuesta
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


#### Suma y multiplicacion por escalar
Esto es igual que en el caso de arrays
$$c+A = c+ \begin{bmatrix} a_{1,1}&a_{1,2}&\cdots& a_{1,n}\\ a_{2,1}&a_{2,2}&\cdots& a_{2,n}\\ \vdots & \vdots & \cdots & \vdots  \\  a_{m,1}&a_{m,2}&\cdots& a_{m,n} \end{bmatrix} = \begin{bmatrix} c+a_{1,1}&c+a_{1,2}&\cdots& c+a_{1,n}\\ c+a_{2,1}&c+a_{2,2}&\cdots& c+a_{2,n}\\ \vdots & \vdots & \cdots & \vdots  \\  c+a_{m,1}&c+a_{m,2}&\cdots& c+a_{m,n} \end{bmatrix}$$  

$$kA = k \begin{bmatrix} a_{1,1}&a_{1,2}&\cdots& a_{1,n}\\ a_{2,1}&a_{2,2}&\cdots& a_{2,n}\\ \vdots & \vdots & \cdots & \vdots  \\  a_{m,1}&a_{m,2}&\cdots& a_{m,n} \end{bmatrix} = \begin{bmatrix} k\,a_{1,1}&k\,a_{1,2}&\cdots& k\,a_{1,n}\\ k\,a_{2,1}&k\,a_{2,2}&\cdots& k\,a_{2,n}\\ \vdots & \vdots & \cdots & \vdots  \\  k\,a_{m,1}&k\,a_{m,2}&\cdots& k\,a_{m,n} \end{bmatrix}$$  
En forma de sumatoria:  
$$c+B = c +\sum_{i=1,j=1}^{m,n} b_{ij}=\sum_{i=1,j=1}^{m,n} (c+b_{ij})$$  

$$kB = k\, \sum_{i=1,j=1}^{m,n} b_{ij}=\sum_{i=1,j=1}^{m,n} (k\,b_{ij})$$


In [24]:
# Creamos una matriz de 3x3 con todos sue elementos en 1
matriz1 = np.ones((3,3), dtype=int)
# La mostramos
print(matriz1)
# le sumamos un escalar
matriz3 = 2 + matriz1
# La mostramos
print(matriz3)
# la multiplicamos por un escalar
matriz6 = 6 * matriz1
# La mostramos
print(matriz6)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[3 3 3]
 [3 3 3]
 [3 3 3]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


La transposicion tiene algunas propiedades:
$$(A+B)^T = A^T + B^T$$
$$(A^T)^T = A$$
$$(kA)^T = k(A^T) \text{siendo k un escalar}$$

#### Suma y multiplicacion por un vector por elementos
Normalmente es necesario que las dimensiones de las estructuras de datos que queremos sumar o multiplicar deben ser coincidentes o que uno de ellos sea un escalar. Pero como ya hemos visto, *numpy* nos da cierta flexibilidad gracias al **broadcasting**  
*Numpy* expande el vector hacia el eje de las filas. Por lo tanto el vector y la matriz deben coincidir en el *numero de columnas*  
Veamos esto:  
Sean
$$v=(v_1, v_2, v_3,\cdots, v_n)$$
y  
$$A=\begin{bmatrix} a_{1,1}&a_{1,2}&\cdots& a_{1,n}\\ a_{2,1}&x_{2,2}&\cdots& a_{2,n}\\ \vdots & \vdots & \cdots & \vdots  \\  a_{m,1}&a_{m,2}&\cdots& a_{m,n} \end{bmatrix}$$  
La matriz suma resultante sera  
$$B=v+A=(v_1, v_2, v_3,\cdots, v_n)+\begin{bmatrix} a_{1,1}&a_{1,2}&\cdots& a_{1,n}\\ a_{2,1}&a_{2,2}&\cdots& a_{2,n}\\ \vdots & \vdots & \cdots & \vdots  \\  a_{m,1}&a_{m,2}&\cdots& a_{m,n} \end{bmatrix}=\begin{bmatrix} v_{1}&v_{2}&\cdots& v_{n}\\ v_{1}&v_{2}&\cdots& v_{n}\\ \vdots & \vdots & \cdots & \vdots  \\  v_{1}&v_{2}&\cdots& v_{n} \end{bmatrix} +\begin{bmatrix} a_{1,1}&a_{1,2}&\cdots& a_{1,n}\\ a_{2,1}&x_{2,2}&\cdots& a_{2,n}\\ \vdots & \vdots & \cdots & \vdots  \\  a_{m,1}&a_{m,2}&\cdots& a_{m,n} \end{bmatrix}=\begin{bmatrix} v_1+a_{1,1}&v_2+a_{1,2}&\cdots& v_n+a_{1,n}\\ v_1+a_{2,1}&v_2+x_{2,2}&\cdots& v_n+a_{2,n}\\ \vdots & \vdots & \cdots & \vdots  \\  v_1+a_{m,1}&v_2+a_{m,2}&\cdots&v_n+ a_{m,n} \end{bmatrix}$$  
  
En el caso de la multiplicacion por elementos  
$$B=v*A=(v_1, v_2, v_3,\cdots, v_n)*\begin{bmatrix} a_{1,1}&a_{1,2}&\cdots& a_{1,n}\\ a_{2,1}&a_{2,2}&\cdots& a_{2,n}\\ \vdots & \vdots & \cdots & \vdots  \\  a_{m,1}&a_{m,2}&\cdots& a_{m,n} \end{bmatrix}=\begin{bmatrix} v_{1}&v_{2}&\cdots& v_{n}\\ v_{1}&v_{2}&\cdots& v_{n}\\ \vdots & \vdots & \cdots & \vdots  \\  v_{1}&v_{2}&\cdots& v_{n} \end{bmatrix} *\begin{bmatrix} a_{1,1}&a_{1,2}&\cdots& a_{1,n}\\ a_{2,1}&x_{2,2}&\cdots& a_{2,n}\\ \vdots & \vdots & \cdots & \vdots  \\  a_{m,1}&a_{m,2}&\cdots& a_{m,n} \end{bmatrix}=\begin{bmatrix} v_1\,a_{1,1}&v_2\,a_{1,2}&\cdots& v_n\,a_{1,n}\\ v_1\,a_{2,1}&v_2\,x_{2,2}&\cdots& v_n\,a_{2,n}\\ \vdots & \vdots & \cdots & \vdots  \\  v_1\,a_{m,1}&v_2\,a_{m,2}&\cdots&v_n\, a_{m,n} \end{bmatrix}$$  

Como podemos ver, estas operaciones son **conmutativas**  
Veamos como hacer esto en codigo:

In [25]:
# Creamos una matriz de 3x3 con todos sus elementos en 1
matriz1 = np.ones((3,3), dtype=int)
# La mostramos
print(matriz1)
# Ahora creamos un array con 3 columnas
v = np.array([1,2,3])
# Realizamos la suma
z = v + matriz1
# mostramos la suma
print(z)
# Realizamos el producto
w = matriz1 * v
# Mostramos el resultado
print(w)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[2 3 4]
 [2 3 4]
 [2 3 4]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


#### Suma de matrices
La suma de matrices solo tiene sentido cuando ambas matrices tienen las mismas dimensiones.  
Esto se puede ver en la definicion:  
$$C=A+B=\begin{bmatrix} a_{1,1}&a_{1,2}&\cdots& a_{1,n}\\ a_{2,1}&a_{2,2}&\cdots& a_{2,n}\\ \vdots & \vdots & \cdots & \vdots  \\  a_{m,1}&a_{m,2}&\cdots& a_{m,n} \end{bmatrix} + \begin{bmatrix} b_{1,1}&b_{1,2}&\cdots& b_{1,n}\\ b_{2,1}&b_{2,2}&\cdots& b_{2,n}\\ \vdots & \vdots & \cdots & \vdots\\b_{m,1}&b_{m,2}&\cdots& b_{m,n} \end{bmatrix} = \begin{bmatrix} a_{1,1}+b_{1,1}&a_{1,2}+b_{1,2}&\cdots& a_{1,n}+b_{1,n}\\ a_{2,1}+b_{2,1}&x_{2,2}+b_{2,2}&\cdots& a_{2,n}+b_{2,n}\\ \vdots & \vdots & \cdots & \vdots  \\  a_{m,1}+b_{m,1}&a_{m,2}+b_{m,2}&\cdots& a_{m,n}+b_{m,n} \end{bmatrix}$$  
En forma de sumatorias:  
$$C=A+B=\sum_{i=1,j=1}^{m,n} a_{ij}+\sum_{i=1,j=1}^{m,n} b_{ij}=\sum_{i=1,j=1}^{m,n} (a_{ij}+b_{ij})$$  
Usando *numpy* esto se ve asi:

In [26]:
# Creamos dos matrices de 3x3
array1 = np.arange(1, 10, dtype=np.int64)
matriz1= array1.reshape(3,3)
array2 = np.arange(10, 19, dtype=np.int64)
matriz2= array2.reshape(3,3)
# Ahora las sumamos
matriz3 = matriz2 + matriz3
print(matriz3)

[[13 14 15]
 [16 17 18]
 [19 20 21]]


#### Producto de matrices
Al igual que con la suma, el producto de matrices solo tiene sentido cuando ambas matrices tienen las mismas dimensiones. 
Y tambien tenemos dos tipos de producto: 
1. **Producto entre elementos (Hadamard)** es cuando cada elemento de cada matriz se multiplica por el correspondiente de la otra matriz
2. **Producto Matricial** es cuando multiplicamos dos matrices y el resultado es una combinacion de todos los elementos en forma vertical y horizontal

##### <ins>Producto Hadamard</ins>
Es la multiplicacion elemento a elemento entre matrices de las mismas dimensiones.
Esto se puede ver en la definicion:  
$$C=A*B=\begin{bmatrix} a_{1,1}&a_{1,2}&\cdots& a_{1,n}\\ a_{2,1}&a_{2,2}&\cdots& a_{2,n}\\ \vdots & \vdots & \cdots & \vdots  \\  a_{m,1}&a_{m,2}&\cdots& a_{m,n} \end{bmatrix} * \begin{bmatrix} b_{1,1}&b_{1,2}&\cdots& b_{1,n}\\ b_{2,1}&b_{2,2}&\cdots& b_{2,n}\\ \vdots & \vdots & \cdots & \vdots\\b_{m,1}&b_{m,2}&\cdots& b_{m,n} \end{bmatrix} = \begin{bmatrix} a_{1,1}\,b_{1,1}&a_{1,2}\,b_{1,2}&\cdots& a_{1,n}\,b_{1,n}\\ a_{2,1}\,b_{2,1}&x_{2,2}\,b_{2,2}&\cdots& a_{2,n}\,b_{2,n}\\ \vdots & \vdots & \cdots & \vdots  \\  a_{m,1}\,b_{m,1}&a_{m,2}\,b_{m,2}&\cdots& a_{m,n}\,b_{m,n} \end{bmatrix}$$  
En forma de sumatorias:  
$$C=A*B=\sum_{i=1,j=1}^{m,n} (a_{ij}\,b_{ij})$$  
Usando *numpy* esto se ve asi:

In [27]:
# Creamos dos matrices de 3x3
array1 = np.arange(1, 10, dtype=np.int64)
matriz1= array1.reshape(3,3)
array2 = np.arange(10, 19, dtype=np.int64)
matriz2= array2.reshape(3,3)
# Ahora las multiplicamos
matriz3 = matriz2 * matriz1
print(matriz1)
print(matriz2)
print(matriz3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


*Numpy* tiene un metodo especifica para realizar la multiplicacion por elementos, es *np.multiply(array1, array2)* Y como vemos por el tipado, funciona tanto en matrices como en vectores.

In [28]:
# Creamos dos matrices de 3x3
array1 = np.arange(1, 10, dtype=np.int64)
matriz1= array1.reshape(3,3)
array2 = np.arange(10, 19, dtype=np.int64)
matriz2= array2.reshape(3,3)
# Ahora las multiplicamos
print(matriz1)
print(matriz2)
matriz3 = np.multiply(matriz2, matriz1)
print(matriz3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


##### <ins>Producto Matricial</ins>
Se denomina *matriz producto* C de la matriz A $a_{ij}\in M_{mxn}$ por la matriz B $b_{ij}\in M_{nxp}$ es la matris formada por lo elementos $c_{ij}\in M_{mxp}$ siempre y cuando $n$ sea el mismo en ambas matrices  
En otras palabras la multiplicacion de unas matrices tales que el numero de columnas de la primera sea igual al numero de filas de la segunda, producen una matriz cuyas filas son las que tenia la primera matriz y cuyas columnas son las que tenia la segunda matriz.  
La [academia Kahn](https://es.khanacademy.org/math/precalculus/x9e81a4f98389efdf:matrices/x9e81a4f98389efdf:properties-of-matrix-multiplication/a/matrix-multiplication-dimensions) tiene una muy buena explicacion de esta relacion que recomiendo ver (link valido a septiembre de 2022)  
Como la representacion en matrices de esta condicion es muy dificil de ajustar a una pagina, veremos como se calcula cada elemento mediante la representacion de sumatoria.  
Volvamos a nuestras matrices A y B  
$$A\mid a_{ij}\in M_{mxn}$$
$$B\mid b_{ij}\in M_{nxp}$$
Entonces 
$$C=AB\mid c_{ij}\in M_{mxp}$$
y
$$c_{ij} = \sum_{k}^n a_{ik}b_{kj}$$  
Veamos un ejemplo  
$$A=\begin{bmatrix}1&2\\3&4\end{bmatrix}$$
$$B=\begin{bmatrix}1&1\\0&2\end{bmatrix}$$  
  
Como vemos, podemos hacer el producto porque las dimensiones estan de acuerdo  

$$C=A\cdot B=\begin{bmatrix}1&2\\3&4\end{bmatrix}\cdot\begin{bmatrix}1&1\\0&2\end{bmatrix}=\begin{bmatrix}1\cdot1+2\cdot0&1\cdot1+2\cdot2\\3\cdot1+4\cdot0&3\cdot1+4\cdot2\end{bmatrix}=\begin{bmatrix}1&5\\3&11\end{bmatrix}$$  
  
Notemos que esta operacion **no es conmutativa** e incluso, cuando no se cumple la condicion de las dimensiones **puede no estar definida**  
  
En *numpy* usamos el metodo *np.matmul(array1, array2)* Que como vemos tambien opera en vectores.  
Existe tambien el operador $@$ que es un atajo de *np.matmul()*

In [29]:
# Para este ejemplo creamos las dos matrices cuadradas
# usamos matmul
matriz_a = np.array([[1,2],[3,4]])
matriz_b = np.array([[1,1],[0,2]])
print(matriz_a)
print(matriz_b)
matriz_c = np.matmul(matriz_a,matriz_b)
print(matriz_c)

[[1 2]
 [3 4]]
[[1 1]
 [0 2]]
[[ 1  5]
 [ 3 11]]


In [30]:
# Para este ejemplo creamos las dos matrices cuadradas
# usamos @
matriz_a = np.array([[1,2],[3,4]])
matriz_b = np.array([[1,1],[0,2]])
print(matriz_a)
print(matriz_b)
matriz_c = matriz_a @ matriz_b
print(matriz_c)

[[1 2]
 [3 4]]
[[1 1]
 [0 2]]
[[ 1  5]
 [ 3 11]]


La multiplicacion matricial tiene las siguientes propiedades:  
Distributiva con la suma $A(B+C) = AB+AC$  
Asociativa $A(BC) = (AB)C$  
La trasposicion de una multiplicacion de matrices tiene la siguiente forma  
$(AB)^T = B^T A^T \;\text{(Notese el cambio de orden)}$

Existen algunas matrices especiales  
##### <ins>Matriz identidad</ins>
Es una forma de generalizar el concepto de *unidad* a matrices.  
Es una matriz cuadrada (numero igual de columnas que de filas) donde los elementos de la diagonal hacia derecha son todos de valor 1, y los demas valen 0.
Formalmente $I \vert i_{ij} \in M_{nxn} , i_{ij} = 1\; \forall\; i=j \quad\text{y}\quad i_{ij}=0\; \forall\; i\neq j$  
Su forma es:  
$$I=\begin{bmatrix}1&0&\cdots & 0\\0&1&\cdots & 0\\ \vdots&\vdots&\cdots&\vdots\\0&0&\cdots & 1\end{bmatrix}$$  
En python la podemos definir con *np.eye()*

In [31]:
# Creamos una matriz identidad de 4x4
matriz_i = np.eye(4)
# laa mostramos
print(matriz_i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


##### <ins>Matriz nula</ins>
Es la generalizacion del cero a matrices.  
Consiste en una matriz donde todos sus elementos son cero.
