# Algebra lineal con numpy

Raul Marusca raulrm@gmail.com

github: https://github.com/raulrm/algebra_numpy

LinkedIn: https://www.linkedin.com/in/raul-marusca/

## Contenido
1. Notación y contenidos básicos  
    1. Notación básica
    2. Contenidos básico
    3. Escalares
    4. Vectores
    5. Matrices
  
2. Multiplicación de Matrices
    1. Producto entre vectores
    2. Producto entre vector y matriz
    3. Producto entre matrices
  
3. Operaciones  
    1. La matriz identidad y la matriz diagonal
    2. Transposición
    3. Matrices simétricas
    4. Traza
    5. Norma
    6. Independencia lineal y Rango
    7. Inversa de una matriz 
    8. Matrices ortogonales 
    9. El determinante
    10. Formas cuadráticas 
    11. Matrices semi-definidas positivas
    12. AutoValores y AutoVectores
    13. AutoValores y AutoVectores de matrices simétricas  
4. Calculo matricial
    1. Gradiente
    2. Hessiano
    3. Gradiente y Hesiano de formas cuadráticas y lineales
    4. Mínimos cuadrados
    5. Gradiente y Determinante
    6. AutoValores como optimizadores

In [2]:
import numpy as np

## Notación y contenidos básicos


### Notacion Basica

### Escalares
En algebra, los escalares son los números con los que trabajamos en el dia a dia.  
Son representados por un numero simple y usando letras minúsculas.  
Ejemplos de escalares son:
- $x \in \mathbb{R}$ - Numero real
- $z \in \mathbb{Z}$ - Numero entero
- $y \in \{0,1,...C\}$ - Conjunto finito
- $u \in [0,1]$ - Conjunto cerrado

En código los podemos ver como:

In [2]:
x = 1.2345
print(x)
z = int(4)
print(z)


1.2345
4


Numpy no tiene una forma directa de definir Conjuntos. Para solucionar eso debemos emplear código que compruebe los valores limites de cada variable.  

#### Suma escalares
Es la suma comun 
$$a+b = c$$
Tembien definiendo el *negativo* podemos definir la resta
$$a + (-b) = c$$
$$a-b = c$$

In [3]:
# En python (funciona con enteros y de coma flotante)
# Tambien con complejos pero no veremos ese type
a = 4
b = 2
c = a + b
print(c) 

c = a - b
print(c) 

6
2


#### Multiplicacion de escalares
La multiplicación, explicada de forma sencilla, consiste en que cuando multiplicamos, por ejemplo, 6×2, estaríamos realizando la siguiente operación 6+6. En otro caso, si multiplicásemos 5×7, estaríamos sumando 5+5+5+5+5+5+5 (sumado 7 veces el numero 5)  
Un caso especial es cuando el o los escalares que estamos multiplicando no son numeros enteros. Que tiene varias formas de resolverse.  
Se nomina como:  
$$a \dot b= c$$
Veamos como se multiplican dos o mas escalares en python 

In [4]:
# Definamos los escalares
a = 4
b = 2
# Y la operacion
c = a*b
print(c)

8


### Vectores
Usualmente consideramos a los vectores como vectores **columna**. Se muestran como letras en minuscula y ocasionalmente con letras en negrita.  
La dimension se describe con las letras $d$, $D$, $n$ o $p$ Nosotros usaremos $n$  
Cada uno de los elementos que componen el vector se determinan por un subindice $x_i$  
Un vector de componentes real se denota como:  
$$\textbf{x} \in \mathbb{R}^n$$
En su forma columna
$$\textbf{x} = \begin{bmatrix} x_{1}\\x_{2}\\x_{3}\\\vdots\\x_{d}\end{bmatrix}$$
o en su forma traspuesta  
$$x = ( x_{1},x_{2},x_{3},\dots,x_{d} )^T$$  

En *Python* los vectores se pueden definir con listas o conjuntos, pero estas estructuras de datos nativas no tienen todos los metodos matematicos necesarios para operar algebraicamente. Y seria necesario desarrollar mucho codigo para ello.   
Por suerte ese codigo ya esta escrito y optimizado en algunas librerias adicionales, nosotros vamos a usar la libreria *numpy* y alli los vectores se definen con el metodo **.array()**  
Veamos como:

In [5]:
# Primero creamos una lista con loscomponentes del vector 
# (o la puede generar nuestro programma)
valores_x = [8.9, 2.5, 23.4,17.7, 11, 4, 13]
# Luego iniciamos el array
# notemos que estamos llamando al metodo .array() de el objeto np (numpy) 
x = np.array(valores_x)
print(x)

[ 8.9  2.5 23.4 17.7 11.   4.  13. ]


In [6]:
# Tambien podemos crearlo directamente
x = np.array([8.9, 2.5, 23.4,17.7, 11, 4, 13])
print(x)

[ 8.9  2.5 23.4 17.7 11.   4.  13. ]


Podemos ver como *numpy* detecta que el tipo mas conveniente para todos los elementos del array es *float*  
Esto se puede cambiar definiendo el *tipo*  con el que se va a guardar cada elemento.  
Recordemos que las listas en Python pueden tener elementos de cualquier tipo (o sea son **heterogeneas**), en los arrays numpy siempre son del mismo tipo. 
Definimos el tipo a utilizar usando el parametro *dtype=*

In [7]:
# creamos un array de elementos enteros
x = np.array([8, 2, 23,17, 11, 4, 13], dtype=np.int64)
print(x)

[ 8  2 23 17 11  4 13]


np.int64 es un numero entero con signo de 64 bits. Hay muchos otros y siempre debemos usar el correcto para la aplicacion que estamos creando.  
Para ver cuales tipos estan disponibles podemos hacer:  

In [8]:
# listar todos los tipos numericos que soporta numpy
np.sctypes

{'int': [numpy.int8, numpy.int16, numpy.int32, numpy.int64],
 'uint': [numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64],
 'float': [numpy.float16, numpy.float32, numpy.float64, numpy.float128],
 'complex': [numpy.complex64, numpy.complex128, numpy.complex256],
 'others': [bool, object, bytes, str, numpy.void]}

numpy ademas tiene otras formas para crear arrays con funciones que lo crean vacios o con algun valor predefinido.  
Veamos cuales son:  
1. Arange() arange(comienzo, fin, paso, dtype) Nunca incluye el valor *fin* en el array

In [9]:
# Arrays con un rango de valores
array_arange = np.arange(10)
print(array_arange)

[0 1 2 3 4 5 6 7 8 9]


Extendemos un poco mas el ejemplo generando un array de numeros impares

In [10]:
# Arrays con un rango de valores con primer valor, valor final y paso
# aprovechamos para definir un tipo de datos
array_arange = np.arange(1, 10, 2, dtype=np.int8)
print(array_arange)

[1 3 5 7 9]


2. Linspace() linspace(comienzo, fin, cantidad, dtype) Siempre incluye *comienzo* y *fin* en el array

In [11]:
# genera cantidad de valores entre dos limites
array_linspace = np.linspace(1., 6., 8)
print(array_linspace)

[1.         1.71428571 2.42857143 3.14285714 3.85714286 4.57142857
 5.28571429 6.        ]


Ahora que ya sabemos como crear array de 1 dimension (o $\mathbb{R}^n$) vamos a ver como podemos realizar algunas operaciones matematicas con ellos

#### Suma de escalar y vector
En algebra comun definimos a la suma de un escalar con un vector como:  
Sea *a* un escalar y $x=(x_1, x_2,...x_n)^T$ un vector de dimension *n* la suma $y=a+x$ es igual a:  

$$\textbf{y} = a +  \begin{bmatrix} x_{1}\\x_{2}\\x_{3}\\\vdots\\x_{n}\end{bmatrix}= \begin{bmatrix} a +x_{1}\\a+x_{2}\\a+x_{3}\\\vdots\\a+x_{n}\end{bmatrix}$$   
O sea que $y$ es tambien un vector de dimension $n$  
Notemos tambien que la suma es **conmutativa** es decir, que $a+x=x+a$  

Hagamos un ejemplo numerico:  
Sea $a=5$ y $x=(4, 3, -5)^T$
$$\textbf{y} = 5 +  \begin{bmatrix} 4\\3\\-5\end{bmatrix}= \begin{bmatrix} 5 +4\\5+3\\5+(-5)\end{bmatrix}= \begin{bmatrix} 9\\8\\0\end{bmatrix}$$ 
Veamos como es esto en python  

In [12]:
# Primero el escalar
a = 5
# Ahora el array
x = np.array([4, 3, -5], dtype=np.int64)
# Veamos que hay en el vector x
print(x)
# Hacemos la cuenta
y = a + x
# Veamos que resultado obtenemos
print(y)

[ 4  3 -5]
[9 8 0]


#### Suma de Vectores
Definimos a la suma de vectores como: 
Sea $x=(x_1, x_2,...x_n)^T$ un vector de dimension *n* y sea $y=(y_1, y_2,...y_n)^T$ **tambien** un vector de dimension **n** (notese que esto es importante, ambos deben ser de la misma dimension) decimos entonces que $w=x+y$ es tambien un vector de dimension *n* cuyos elementos son:  

$$\textbf{w} = x+ y =\begin{bmatrix} x_{1}\\x_{2}\\x_{3}\\\vdots\\x_{n}\end{bmatrix} + \begin{bmatrix} y_{1}\\y_{2}\\y_{3}\\\vdots\\y_{n}\end{bmatrix}= \begin{bmatrix} x_{1} + y_1\\x_{2} + y_2\\x_{3}+y_3\\\vdots\\x_{n}+y_n\end{bmatrix}$$  
Podemos apreciar tambien que la suma de vectores es conmutativa, es decir: $x+y=y+x$  

Vayamos a un ejemplo con valores  
Sea $x=(6, 3, 5, 4)^T$ y $y=(2, -1, 4, 8)^T$

$$\textbf{w} = x+ y =\begin{bmatrix} 6\\3\\5\\4\end{bmatrix} + \begin{bmatrix} 2\\-1\\4\\8\end{bmatrix}= \begin{bmatrix} 6 + 2\\3+(-1)\\5+4\\4+8\end{bmatrix}= \begin{bmatrix} 8\\2\\9\\12\end{bmatrix}$$  

En codigo:

In [13]:
# Hacemos x
x = np.array([6, 3, 5, 4], dtype=np.int64)
# Hacemos y
y = np.array([2, -1, 4, 8], dtype=np.int64)
# realizamos la suma de vectores
w = x +y 
print(w)

[ 8  2  9 12]


#### Multiplicacion de escalar y vector
En algebra comun definimos a la multiplicacion de un escalar con un vector como:  
Sea *a* un escalar y $x=(x_1, x_2,...x_n)^T$ un vector de dimension *n* el producto $y=a\,x$ es igual a:  

$$\textbf{y} = a\,\begin{bmatrix} x_{1}\\x_{2}\\x_{3}\\\vdots\\x_{n}\end{bmatrix}= \begin{bmatrix} a\,x_{1}\\a\,x_{2}\\a\,x_{3}\\\vdots\\a\,x_{n}\end{bmatrix}$$   
O sea que $y$ es tambien un vector de dimension $n$  
Notemos tambien que el producto es **conmutativo** es decir, que $a\,x=x\,a$  

Hagamos un ejemplo numerico:  
Sea $a=5$ y $x=(4, 3, -5)^T$
$$\textbf{y} = 5\,\begin{bmatrix} 4\\3\\-5\end{bmatrix}= \begin{bmatrix} 5\;4\\5\;3\\5\,(-5)\end{bmatrix}= \begin{bmatrix} 20\\15\\-25\end{bmatrix}$$ 
Veamos como es esto en python 

In [14]:
# Hacemos el escalar
a = 5
# Hacemos x
x = np.array([4, 3, -5], dtype=np.int64)
# realizamos el producto de vectores
y = a*x 
print(y)

[ 20  15 -25]


#### Multiplicacion de Vectores
Ok, aqui ya entramos en algunos problemas. Es que existen dos formas de hacer el producto entre vectores:
1. **Producto Interno** es cuando multiplicamos dos vectores y nuestro resultado es un escalar.
2. **Producto Externo** es cuando multiplicamos dos vectores y nuestro resultado es otro vector o matriz.  

Veamos como es eso  
##### <ins>Producto interno</ins>
Se define al producto interno entre dos vectores $x=(x_1, x_2,...x_n)^T$ y $y=(y_1, y_2,...y_n)^T$ al escalar $v$ que surge de realizar
$$v = \sum_{i=1}^n x_i\;y_i$$
O de otra forma
$$v = x \cdot y =\begin{bmatrix} x_{1}\\x_{2}\\x_{3}\\\vdots\\x_{n}\end{bmatrix} \cdot \begin{bmatrix} y_{1}\\y_{2}\\y_{3}\\\vdots\\y_{n}\end{bmatrix}= x_{1} \; y_1+x_{2}\;y_2+x_{3}\;y_3+ \cdots + x_{n}\;y_n$$  
Podemos notar que este producto es **conmutativo** es decir $x\cdot y=y\cdot x$  

Tambien tenemos una forma mas concisa para denotar al producto interno usando notacion matricial
$$v= x^Ty$$
$$v = x^Ty = [x_{1},x_{2},x_{3},\dots,x_{n}]\begin{bmatrix} y_{1}\\y_{2}\\y_{3}\\\vdots\\y_{n}\end{bmatrix}=\sum_{i=1}^n x_i\;y_i$$  
Se puede tambien expresar esta operacion como  
$$x^T y = y^T x$$
ya que es conmutativo  

El producto interno tambien es conocido por *producto punto* 

Hagamos esa cuenta con valores  
Sea $x=(4, 3, -5)^T$ y $y=(2, -1, 4)^T$, entonces:  
$$v = x \cdot y =\begin{bmatrix} 4\\3\\-5\end{bmatrix} \cdot \begin{bmatrix} 2\\-1\\4\end{bmatrix}= 4 \cdot 2+3\cdot (-1)+(-5)\cdot 4 = 8-3-20 = -15$$  
En Python para realizar esta operacion se emplea el metodo *np.inner(array1, array2)* (tambien existe el alias *np.dot()*)

In [4]:
# Definimos x 
x = np.array([4, 3, -5], dtype =np.int64)
# definimos y 
y = np.array([2, -1, 4], dtype =np.int64)
# Ahora realizamos la operacion
v = np.inner(x, y)
print(v)

z = np.multiply(x,y)
print(z)


-15
[  8  -3 -20]


np.inner() tambien admite la multiplicacion de escalares. De paso mostramos que *np.dot()* funciona igual

In [16]:
# Definimos los escalares
a, b = 4, 2
# Hacemos el producto inner
c = np.inner(a, b)
print(c)
# Hacemos el producto dot
c = np.dot(a, b)
print(c)

8
8


Nota:  
La mutiplicacion de un escalar por un array en numpy oculta un proceso que se llama **Broadcasting** en el cual el escalar es convertido en un array de las misma s dimensiones que el que se esta multiplicando y luego se ejecuta 

##### <ins>Producto externo</ins>
Se define al producto punto entre dos vectores $x=(x_1, x_2,...x_m)^T$ y $y=(y_1, y_2,...y_n)^T$ (*n* y *m* pueden tener valores distintos) a la matriz $v$ de dimensiones *m x n* que resulta de hacer  

$$v = xy^T$$  

Nota: En algunos textos el producto externo se denota con el simbolo $\otimes$ Pero en nuestro caso el uso de la notacion matricial deja en claro que tipo de producto es.  

El calculo del producto externo se desarrolla de la siguiente forma:  

$$xy^T = \begin{bmatrix} x_{1}\\x_{2}\\x_{3}\\\vdots\\x_{m}\end{bmatrix} [y_1, y_2, y_3, \dots, y_n ] = \begin{bmatrix} x_1 y_1 & x_1 y_2 & x_1 y_3 & \cdots & x_1 y_n \\ x_2 y_1 & x_2 y_2 & x_2 y_3 & \cdots & x_2 y_n \\ x_3 y_1 & x_3 y_2 & x_3 y_3 & \cdots & x_3 y_n \\ \vdots & \vdots & \vdots & \cdots & \vdots \\ x_m y_1 & x_m y_2 & x_m y_3 & \cdots & x_m y_n \\ \end{bmatrix}$$  

Como vemos, salvo que uno o dos de los arrays sean de dimension 1, el resultado del producto externo es una matriz  
Otro detalle a tener en cuenta es que esta operacion no es conmutativa, es decir:  
$$xy^T \neq yx^T$$
  
Hagamos un ejemplo numerico con los vectores ya conocidos  
Sea $x=(4, 3, -5)^T$ y $y=(2, -1, 4)^T$, entonces:  
$$v = xy^T =\begin{bmatrix} 4\\3\\-5\end{bmatrix} \cdot [2\; -1\; 4] = \begin{bmatrix} 4\cdot 2 & 4\cdot -1 & 4\cdot 4\\ 3\cdot 2& 3 \cdot -1& 3\cdot 4\\-5\cdot 2& -5 \cdot -1& -5\cdot 4\end{bmatrix}= \begin{bmatrix} 8 & -4 & 16\\ 6& -3& 12\\-10& 5& -20\end{bmatrix}$$ 

Para realizar esta operacion en numpy se emplea el metodo .outer(array1, array2)


In [17]:
# Definimos x 
x = np.array([4, 3, -5], dtype =np.int64)
# definimos y 
y = np.array([2, -1, 4], dtype =np.int64)
# Ahora realizamos la operacion
v = np.outer(x, y)
print(v)

[[  8  -4  16]
 [  6  -3  12]
 [-10   5 -20]]


### Matrices
Como ya hemos visto, las matrices son arreglos bidimensionales de numeros.  
Por lo general se las denomina con una letra en mayuscula  
Y se accede a sus elementos empleando dos indices (el vertical y el horizontal) $X_{ij}$ o $x_{ij}$  
Unos ejemplos son:
$$X \in \mathrm{R}^{m\times n}$$  
$$V = \begin{bmatrix} 8 & -4 & 16\\ 6& -3& 12\\-10& 5& -20\end{bmatrix}$$  
  
En *numpy* las matrices son un caso de array con 2 dimensiones  
Para crear una matriz con *numpy* disponemos de varias formas:  
. Concatenando arrays

In [18]:
# Definimos 4 arrays de 4 elementos
array1 = [0,1,2,3]
array2 = [4, 5, 6, 7]
array3 = [8, 9, 10, 11]
array4 = [12, 13, 14, 15]
# contruimos el array multidimensional con el metodo *.array()*
matriz1 = np.array([array1, array2, array3, array4])
# Mostramos como quedo
print(matriz1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


. Redimensionando un array existente con el metodo *.reshape()* 

In [19]:
# Creamos un array de una dimension con el metodo .arange()
array_1d = np.arange(16)
# Ahora modificamos sus dimensiones de 1x16 a 4x4
matriz1 = array_1d. reshape(4,4)
# Mostramos como quedo
print(matriz1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


. Creando matrices vacias o unitarias y multiplicando por un escalar  
Para ello usaremos los metodos *.zeros()* y *ones()* Ambos requieren que le pasemos las dimensiones en una tupla y que indiquemos de que tipo van  a ser sus elementos.

In [20]:
# Creamos una matriz de 3x3 con todos sue elementos en cero
matriz0 = np.zeros((3,3), dtype=int)
# Lo mostramos
print(matriz0)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [21]:
# Creamos una matriz de 3x3 con todos sue elementos en 1
matriz1 = np.ones((3,3), dtype=int)
# Lo mostramos
print(matriz1)
# la multiplicamos por un escalar
matriz6 = 6 * matriz1
#La mostramos
print(matriz6)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


#### Transposicion 
La operacion mas basica que podemos realizar con una matriz es la de *trasponerla* Esto consiste en intercambiar filas por columnas.  
La operacion se denota con una letra T o t "elevando" a la matriz
$$A^T$$ 
Esto ya lo vimos en vectores cuando transponiamos un vector columna a un vector fila  
En matrices seria:  

$$ X = \begin{bmatrix} x_{1,1}&x_{1,2}&\cdots& x_{1,n}\\ x_{2,1}&x_{2,2}&\cdots& x_{2,n}\\ \vdots & \vdots & \cdots & \vdots  \\  x_{m,1}&x_{m,2}&\cdots& x_{m,n} \end{bmatrix} \qquad X^T = \begin{bmatrix} x_{1,1}&x_{2,1}&\cdots& x_{m,1}\\ x_{1,2}&x_{2,2}&\cdots& x_{m,2}\\ \vdots & \vdots & \cdots & \vdots  \\  x_{1,n}&x_{2,n}&\cdots& x_{m,n} \end{bmatrix}$$
  
Esta operacion en numpy se hace con el metodo .T de la matriz o vector


In [3]:
# Creamos una matriz cuadrada de 3x3
A = np.arange(9).reshape(3,3)
# La mostramos
print(A)
# Ahora la trasponemos
A = A.T
# Y la volvemos a mostrar traspuesta
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]
